In [1]:
# Load Data Target
import pandas as pd
import time
import numpy as np
ds = pd.read_csv("dataset60.csv")


In [2]:
data = pd.read_csv("dataset60.csv", header = None, names = ["X1", "X2", "X3", "Y"])


In [3]:
dataset = np.array(data) # mengubah tampilan frame pandas menjadi array numpy
#np.set_printoptions(precision = 3, suppress = True) # menampilkan 3 digit angka dibelakang koma

In [4]:
# Load Data Peramalan
from openpyxl import load_workbook

X1=load_workbook('peramalan13.xlsx')
X1=X1.get_sheet_by_name('peramalan_13')
m=X1.max_row
n=X1.max_column
X_1=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        X_1[i,j]=X1.cell(row=i+1,column=j+1).value

data1=np.array(X_1) 

X2=load_workbook('peramalan23.xlsx')
X2=X2.get_sheet_by_name('peramalan_23')
m=X2.max_row
n=X2.max_column
X_2=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        X_2[i,j]=X2.cell(row=i+1,column=j+1).value

data2=np.array(X_2)

X3=load_workbook('peramalan33.xlsx')
X3=X3.get_sheet_by_name('peramalan_33')
m=X3.max_row
n=X3.max_column
X_3=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        X_3[i,j]=X3.cell(row=i+1,column=j+1).value

data3=np.array(X_3)


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  """
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  app.launch_new_instance()
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


In [5]:
data_peramalan= dataset[len(dataset)-12:len(dataset),].copy()

In [6]:
data_peramalan

array([[ 28.09,  77.  , 183.  ,   2.  ],
       [ 27.94,  78.  , 259.  ,   3.  ],
       [ 28.38,  77.  , 220.  ,   3.  ],
       [ 28.61,  77.  , 173.  ,   3.  ],
       [ 28.76,  72.  ,  79.  ,   3.  ],
       [ 28.02,  70.  ,  92.  ,   3.  ],
       [ 27.73,  65.  ,  26.  ,   3.  ],
       [ 28.02,  59.  ,   4.  ,   2.  ],
       [ 29.13,  56.  ,  34.  ,   1.  ],
       [ 30.39,  57.  , 106.  ,   1.  ],
       [ 28.93,  63.  , 208.  ,   1.  ],
       [ 28.55,  71.  , 249.  ,   1.  ]])

In [7]:
data_peramalan[:,0]=data1[:,0]
data_peramalan[:,1]=data2[:,0]
data_peramalan[:,2]=data3[:,0]

In [8]:
data_peramalan

array([[ 28.89517212,  66.95263672, 133.47923279,   2.        ],
       [ 29.10146523,  68.85414886,  83.87404633,   3.        ],
       [ 29.07938766,  70.76222229,  94.0355072 ,   3.        ],
       [ 28.75369644,  71.01674652,  81.34913635,   3.        ],
       [ 28.23332024,  72.85636139,  24.57762337,   3.        ],
       [ 28.26019096,  68.28401947,   4.40391922,   3.        ],
       [ 28.23427963,  66.11540222,  18.92186546,   3.        ],
       [ 29.23192406,  65.65193939, 105.56183624,   2.        ],
       [ 28.379076  ,  66.14350128, 176.16783142,   1.        ],
       [ 27.98853302,  64.74707794, 155.00746155,   1.        ],
       [ 28.03698921,  67.45734406, 211.99664307,   1.        ],
       [ 28.22960281,  68.41078186, 107.55292511,   1.        ]])

In [9]:
def normalization(dataset): # fungsi normalization dg data sebagai input 
    (baris,kolom) = dataset.shape
    mins          = np.zeros(shape = (kolom)) # inisialisasi array dataset tesis minimum
    maxs          = np.zeros(shape = (kolom)) # initiasliasi array dataset tesis maksimum
    for j in range (kolom):
        mins[j] = np.min(dataset[:,j]) # mendapatkan nilai minimum setiap kolom
        maxs[j] = np.max(dataset[:,j]) # mendapatkan nilai maksimum setiap kolom
        
    normalisasi = np.copy(dataset) #mendefinisikan hasil normalisasi 45x3
    for i in range (baris):
        for j in range (kolom):
            normalisasi[i,j] = ((dataset[i,j]-mins[j]) / (maxs[j]-mins[j])) # hasil subtitusi ke dalam rumus normalisasi (Dubey, 2015 
#            np.set_printoptions(precision=11, suppress=True) # menampilkan 11 digit angka dibelakang koma               
    return (normalisasi) # display normalisasi

In [10]:
normalisasi = normalization(data_peramalan)
print(normalisasi)

[[0.72916651 0.27197949 0.62177186 0.5       ]
 [0.8950782  0.50646533 0.3828175  1.        ]
 [0.87732227 0.74176028 0.43176652 1.        ]
 [0.61538438 0.77314705 0.37065469 1.        ]
 [0.19687066 1.         0.09717924 1.        ]
 [0.2184815  0.43615956 0.         1.        ]
 [0.19764226 0.16873553 0.06993475 1.        ]
 [1.         0.1115834  0.48729028 0.5       ]
 [0.31409506 0.17220058 0.82740815 0.        ]
 [0.         0.         0.72547602 0.        ]
 [0.038971   0.33421771 1.         0.        ]
 [0.19388092 0.45179133 0.49688161 0.        ]]


# Testing

In [11]:
def EuclideanDistance(unit, center): # fungsi Euclidean Distance dg inputs unit & center 
    baris = len(unit)
    sum   = 0
    for i in range(baris):
        sum += (unit[i] - center[i]) ** 2
    return np.sqrt(sum)

def sigma(centers, p):
    p              = len(centers)  
    dmax          = 0
    for i in range(p):
        for j in range(p):
            if i == j:
                continue
            dist = EuclideanDistance(centers[i], centers[j])
            if dist > dmax:
                dmax = dist 
    sigma = dmax / np.sqrt(2*p)
    return sigma

def gaussian(ds_training, centers, sigma):
    return np.exp(- EuclideanDistance(ds_training, centers)**2 / (2 * sigma**2))

def Approximation_yu(ds_testing, centers, sigma, phi, w_update):
    (baris, kolom) = ds_testing.shape
    p              = len(centers)
    F              = np.array(np.zeros([baris,1]), dtype=np.float32)
            
    sum7          = 0 
    for i in range (baris):
        for j in range (p):
            sum7   += phi[i,j]*w_update[j]             
        F[i,0]       = sum7                                   
        sum7        = 0   
    return (F, w_update, phi)



In [12]:
# Load Data Center, Phi dan W_update
from openpyxl import load_workbook

Peramalan1=load_workbook('Centers_Clusters.xlsx')
peramalan1=Peramalan1.get_sheet_by_name('centers')
m=peramalan1.max_row
n=peramalan1.max_column
peramalan_1=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        peramalan_1[i,j]=peramalan1.cell(row=i+1,column=j+1).value

centers=peramalan_1

Peramalan2=load_workbook('Phi.xlsx')
peramalan2=Peramalan2.get_sheet_by_name('phi')
m=peramalan2.max_row
n=peramalan2.max_column
peramalan_2=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        peramalan_2[i,j]=peramalan2.cell(row=i+1,column=j+1).value

phi=peramalan_2

Peramalan3=load_workbook('Update_Weights.xlsx')
peramalan3=Peramalan3.get_sheet_by_name('uw')
m=peramalan3.max_row
n=peramalan3.max_column
peramalan_3=np.array(np.zeros([m,n]))
for i in range (0,m):
    for j in range (0,n):
        peramalan_3[i,j]=peramalan3.cell(row=i+1,column=j+1).value

w_update=peramalan_3


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  """
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  app.launch_new_instance()
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


In [13]:
centers.shape

(47, 3)

In [14]:
ds_testing=normalisasi[:,0:3]
print(ds_testing)

[[0.72916651 0.27197949 0.62177186]
 [0.8950782  0.50646533 0.3828175 ]
 [0.87732227 0.74176028 0.43176652]
 [0.61538438 0.77314705 0.37065469]
 [0.19687066 1.         0.09717924]
 [0.2184815  0.43615956 0.        ]
 [0.19764226 0.16873553 0.06993475]
 [1.         0.1115834  0.48729028]
 [0.31409506 0.17220058 0.82740815]
 [0.         0.         0.72547602]
 [0.038971   0.33421771 1.        ]
 [0.19388092 0.45179133 0.49688161]]


In [15]:
approx_y_uji = Approximation_yu(ds_testing, centers, sigma, phi, w_update)
phi_approx_yu    = approx_y_uji[2]
print(phi_approx_yu)

[[1.00000000e+00 1.52022679e-08 3.20320725e-01 ... 2.80432491e-12
  4.96092305e-08 3.91993490e-06]
 [1.52022626e-08 1.00000000e+00 5.09452502e-06 ... 7.33273282e-06
  1.35723885e-05 4.19191338e-06]
 [3.20320785e-01 5.09452184e-06 1.00000000e+00 ... 3.38366917e-08
  5.06116085e-05 1.25415518e-03]
 ...
 [4.96091914e-08 1.35723867e-05 5.06116339e-05 ... 2.37405658e-01
  1.00000000e+00 5.97541571e-01]
 [3.91993399e-06 4.19191156e-06 1.25415600e-03 ... 3.41659114e-02
  5.97541630e-01 1.00000000e+00]
 [6.89698150e-03 1.27120540e-04 1.57339245e-01 ... 1.36044458e-04
  2.53581423e-02 1.13680571e-01]]


In [16]:
phi_approx_yu.shape

(48, 47)

In [17]:
approx_y_uji = Approximation_yu(ds_testing, centers, sigma, phi, w_update)
approx_yu    = approx_y_uji[0]
print(approx_yu)

[[ 4.8670721e-01]
 [ 5.0158256e-01]
 [ 6.9244766e-01]
 [ 1.0019186e+00]
 [ 9.9910867e-01]
 [ 1.0067750e+00]
 [ 4.9229860e-01]
 [ 5.7869041e-01]
 [ 3.4431526e-01]
 [-5.8203592e-04]
 [ 1.2002045e-01]
 [-5.0543588e-02]]


In [18]:
def denormalization(day, approx_y): 
    mins = np.min(day)
    maxs = np.max(day)
    
    hasil = np.copy(approx_y) #mendefinisikan hasil denormalisasi 45x3
    for i in range (len(day)):
        hasil[i]=mins+(approx_y[i]*(maxs-mins))              
    return (hasil)

In [19]:
dayu=np.vstack(data_peramalan[:,3])
print(dayu)

[[2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [20]:
denormalize_ayu = denormalization(dayu, approx_yu) #menampilkan hasil dari fungsi denormalization  
print(denormalize_ayu)

[[1.9734144 ]
 [2.0031652 ]
 [2.3848953 ]
 [3.003837  ]
 [2.9982173 ]
 [3.01355   ]
 [1.9845972 ]
 [2.1573808 ]
 [1.6886306 ]
 [0.9988359 ]
 [1.2400409 ]
 [0.89891285]]


In [21]:
def MAPE(dayu, denormalize_ayu):
    mapeRBF = np.array(np.zeros([1,1]), dtype=np.float32)
    mapeRBF = np.mean(np.absolute(dayu - denormalize_ayu)/dayu) * 100
    
    return(mapeRBF)

In [22]:
mape_RBF = MAPE(dayu, denormalize_ayu)
print(mape_RBF)

16.708971560001373


In [23]:
m  = len(dayu)
gabung   = np.array(np.zeros([m,2]))
gabung[:,0]= dayu[:,0]
gabung[:,1]= denormalize_ayu[:,0]
print(gabung)

[[2.         1.97341442]
 [3.         2.00316525]
 [3.         2.38489532]
 [3.         3.00383711]
 [3.         2.99821734]
 [3.         3.01355004]
 [3.         1.98459721]
 [2.         2.15738082]
 [1.         1.68863058]
 [1.         0.99883592]
 [1.         1.2400409 ]
 [1.         0.89891285]]


In [24]:
(np.absolute(dayu - denormalize_ayu)/dayu)*100

array([[1.32927895e+00],
       [3.32278252e+01],
       [2.05034892e+01],
       [1.27903620e-01],
       [5.94218572e-02],
       [4.51668104e-01],
       [3.38467598e+01],
       [7.86904097e+00],
       [6.88630581e+01],
       [1.16407871e-01],
       [2.40040898e+01],
       [1.01087153e+01]])

In [25]:
import matplotlib.pyplot  as plt
x = np.linspace(0, 12, num=14)

plt.plot(dayu, '-', color ='b', label='Original')
plt.plot(denormalize_ayu, 'k*-', color ='k', label='Forecasting')

plt.xlabel('Index in Month-Year')
plt.ylabel('Classification of Vannamei Shrimp Production')

plt.title('Testing Plot of Vannamei Shrimp Production')

plt.legend()

plt.xlim([0, 12])
plt.ylim([0.5, 5])

plt.show()

<Figure size 640x480 with 1 Axes>