In [11]:
import pandas as pd
import time
import numpy as np

In [16]:
a= [[28.09],
 [27.94],
 [28.38],
 [28.61],
 [28.76],
 [28.02],
 [27.73],
 [28.02],
 [29.13],
 [30.39],
 [28.93],
 [28.55]]
dayu = np.vstack(a)
print(dayu)

[[28.09]
 [27.94]
 [28.38]
 [28.61]
 [28.76]
 [28.02]
 [27.73]
 [28.02]
 [29.13]
 [30.39]
 [28.93]
 [28.55]]


In [17]:
b = [[28.895172],
 [29.101465],
 [29.079388],
 [28.753696],
 [28.23332 ],
 [28.260191],
 [28.23428 ],
 [29.231924],
 [28.379076],
 [27.988533],
 [28.03699 ],
 [28.229603]]
denormalize_ayu = np.vstack(b)
print(denormalize_ayu)

[[28.895172]
 [29.101465]
 [29.079388]
 [28.753696]
 [28.23332 ]
 [28.260191]
 [28.23428 ]
 [29.231924]
 [28.379076]
 [27.988533]
 [28.03699 ]
 [28.229603]]


In [18]:
(m,n)    = np.shape(dayu)
gabung   = np.array(np.zeros([m,2]))
gabung[:,0]= dayu[:,0]
gabung[:,1]= denormalize_ayu[:,0]
print(gabung)

[[28.09     28.895172]
 [27.94     29.101465]
 [28.38     29.079388]
 [28.61     28.753696]
 [28.76     28.23332 ]
 [28.02     28.260191]
 [27.73     28.23428 ]
 [28.02     29.231924]
 [29.13     28.379076]
 [30.39     27.988533]
 [28.93     28.03699 ]
 [28.55     28.229603]]


In [19]:
aaa = np.absolute(dayu - denormalize_ayu)/dayu
aaa

array([[0.02866401],
       [0.04156997],
       [0.02464369],
       [0.00502258],
       [0.01831293],
       [0.00857213],
       [0.01818536],
       [0.04325211],
       [0.02577837],
       [0.07902162],
       [0.03086796],
       [0.01122231]])

In [24]:
np.sum(np.absolute(dayu - denormalize_ayu)/dayu)

0.3351130389465899

In [22]:
np.sum(np.absolute(dayu - denormalize_ayu)/dayu)/12

0.02792608657888249

In [23]:
(np.sum(np.absolute(dayu - denormalize_ayu)/dayu)/12)*100

2.792608657888249