In [1]:
import pandas as pd
import time
import numpy as np
ds = pd.read_csv("dataset60.csv")
ds

27.96  84.0  362.0  2.0
0   28.25  82.0    0.0  2.0
1   28.42  81.0  299.0  3.0
2   28.72  81.0  209.0  3.0
3   28.67  79.0  123.0  3.0
4   28.29  80.0  120.0  3.0
5   27.30  74.0   71.0  2.0
6   27.60  68.0    4.0  2.0
7   28.55  64.0    3.0  2.0
8   30.18  63.0   59.0  1.0
9   29.20  70.0  143.0  1.0
10  27.84  80.0  322.0  1.0
11  27.36  82.0  193.0  2.0
12  27.54  82.0  216.0  3.0
13  28.56  81.0  202.0  3.0
14  28.76  79.0  226.0  3.0
15  29.48  76.0   63.0  3.0
16  28.90  73.0   43.0  3.0
17  28.10  72.0   24.0  3.0
18  27.80  69.0    7.0  2.0
19  28.24  63.0    1.0  1.0
20  29.94  61.0    6.0  2.0
21  30.14  68.0  133.0  1.0
22  28.30  80.0  312.0  1.0
23  28.00  79.0  280.0  3.0
24  27.74  77.0  403.0  3.0
25  28.46  75.0  228.0  3.0
26  28.16  75.0  306.0  3.0
27  28.39  69.0   96.0  3.0
28  28.10  66.0   13.0  3.0
29  27.36  66.0    1.0  3.0
30  27.65  63.0    2.0  2.0
31  28.45  58.0    0.0  1.0
32  29.89  54.0    0.0  3.0
33  30.88  60.0  123.0  1.0
34  29.35  69.0  357.0  1.0
35  29.39  71.0  228.0  2.0
36  28.33  78.0  409.0  3.0
37  29.47  74.0  187.0  3.0
38  29.40  71.0  175.0  3.0
39  29.66  71.0  169.0  3.0
40  28.66  71.0  221.0  3.0
41  28.49  69.0   48.0  3.0
42  28.61  65.0   32.0  2.0
43  29.36  63.0   64.0  1.0
44  28.94  65.0  151.0  1.0
45  28.99  67.0  206.0  1.0
46  28.30  74.0  233.0  1.0
47  28.09  77.0  183.0  2.0
48  27.94  78.0  259.0  3.0
49  28.38  77.0  220.0  3.0
50  28.61  77.0  173.0  3.0
51  28.76  72.0   79.0  3.0
52  28.02  70.0   92.0  3.0
53  27.73  65.0   26.0  3.0
54  28.02  59.0    4.0  2.0
55  29.13  56.0   34.0  1.0
56  30.39  57.0  106.0  1.0
57  28.93  63.0  208.0  1.0
58  28.55  71.0  249.0  1.0

In [2]:
data = pd.read_csv("dataset60.csv", header = None, names = ["X1", "X2", "X3", "Y"])
data

X1    X2     X3    Y
0   27.96  84.0  362.0  2.0
1   28.25  82.0    0.0  2.0
2   28.42  81.0  299.0  3.0
3   28.72  81.0  209.0  3.0
4   28.67  79.0  123.0  3.0
5   28.29  80.0  120.0  3.0
6   27.30  74.0   71.0  2.0
7   27.60  68.0    4.0  2.0
8   28.55  64.0    3.0  2.0
9   30.18  63.0   59.0  1.0
10  29.20  70.0  143.0  1.0
11  27.84  80.0  322.0  1.0
12  27.36  82.0  193.0  2.0
13  27.54  82.0  216.0  3.0
14  28.56  81.0  202.0  3.0
15  28.76  79.0  226.0  3.0
16  29.48  76.0   63.0  3.0
17  28.90  73.0   43.0  3.0
18  28.10  72.0   24.0  3.0
19  27.80  69.0    7.0  2.0
20  28.24  63.0    1.0  1.0
21  29.94  61.0    6.0  2.0
22  30.14  68.0  133.0  1.0
23  28.30  80.0  312.0  1.0
24  28.00  79.0  280.0  3.0
25  27.74  77.0  403.0  3.0
26  28.46  75.0  228.0  3.0
27  28.16  75.0  306.0  3.0
28  28.39  69.0   96.0  3.0
29  28.10  66.0   13.0  3.0
30  27.36  66.0    1.0  3.0
31  27.65  63.0    2.0  2.0
32  28.45  58.0    0.0  1.0
33  29.89  54.0    0.0  3.0
34  30.88  60.0  123.0  1.0
35  29.35  69.0  357.0  1.0
36  29.39  71.0  228.0  2.0
37  28.33  78.0  409.0  3.0
38  29.47  74.0  187.0  3.0
39  29.40  71.0  175.0  3.0
40  29.66  71.0  169.0  3.0
41  28.66  71.0  221.0  3.0
42  28.49  69.0   48.0  3.0
43  28.61  65.0   32.0  2.0
44  29.36  63.0   64.0  1.0
45  28.94  65.0  151.0  1.0
46  28.99  67.0  206.0  1.0
47  28.30  74.0  233.0  1.0
48  28.09  77.0  183.0  2.0
49  27.94  78.0  259.0  3.0
50  28.38  77.0  220.0  3.0
51  28.61  77.0  173.0  3.0
52  28.76  72.0   79.0  3.0
53  28.02  70.0   92.0  3.0
54  27.73  65.0   26.0  3.0
55  28.02  59.0    4.0  2.0
56  29.13  56.0   34.0  1.0
57  30.39  57.0  106.0  1.0
58  28.93  63.0  208.0  1.0
59  28.55  71.0  249.0  1.0

In [3]:
data.shape

(60, 4)

In [4]:
dataset = np.array(data) # mengubah tampilan frame pandas menjadi array numpy
print(dataset) 

[[ 27.96  84.   362.     2.  ]
 [ 28.25  82.     0.     2.  ]
 [ 28.42  81.   299.     3.  ]
 [ 28.72  81.   209.     3.  ]
 [ 28.67  79.   123.     3.  ]
 [ 28.29  80.   120.     3.  ]
 [ 27.3   74.    71.     2.  ]
 [ 27.6   68.     4.     2.  ]
 [ 28.55  64.     3.     2.  ]
 [ 30.18  63.    59.     1.  ]
 [ 29.2   70.   143.     1.  ]
 [ 27.84  80.   322.     1.  ]
 [ 27.36  82.   193.     2.  ]
 [ 27.54  82.   216.     3.  ]
 [ 28.56  81.   202.     3.  ]
 [ 28.76  79.   226.     3.  ]
 [ 29.48  76.    63.     3.  ]
 [ 28.9   73.    43.     3.  ]
 [ 28.1   72.    24.     3.  ]
 [ 27.8   69.     7.     2.  ]
 [ 28.24  63.     1.     1.  ]
 [ 29.94  61.     6.     2.  ]
 [ 30.14  68.   133.     1.  ]
 [ 28.3   80.   312.     1.  ]
 [ 28.    79.   280.     3.  ]
 [ 27.74  77.   403.     3.  ]
 [ 28.46  75.   228.     3.  ]
 [ 28.16  75.   306.     3.  ]
 [ 28.39  69.    96.     3.  ]
 [ 28.1   66.    13.     3.  ]
 [ 27.36  66.     1.     3.  ]
 [ 27.65  63.     2.     2.  ]
 [ 28.45

In [5]:
def normalization(dataset): # fungsi normalization dg data sebagai input 
    (baris,kolom) = dataset.shape
    mins          = np.zeros(shape = (kolom)) # inisialisasi array dataset tesis minimum
    maxs          = np.zeros(shape = (kolom)) # initiasliasi array dataset tesis maksimum
    for j in range (kolom):
        mins[j] = np.min(dataset[:,j]) # mendapatkan nilai minimum setiap kolom
        maxs[j] = np.max(dataset[:,j]) # mendapatkan nilai maksimum setiap kolom
        
    normalisasi = np.copy(dataset) #mendefinisikan hasil normalisasi 60x3
    for i in range (baris):
        for j in range (kolom):
            normalisasi[i,j] = ((dataset[i,j]-mins[j]) / (maxs[j]-mins[j])) # hasil subtitusi ke dalam rumus normalisasi (Dubey, 2015 
    return (normalisasi) # display normalisasi

In [6]:
normalisasi = normalization(dataset)
print(normalisasi)

[[0.18435754 1.         0.88508557 0.5       ]
 [0.26536313 0.93333333 0.         0.5       ]
 [0.31284916 0.9        0.73105134 1.        ]
 [0.39664804 0.9        0.51100244 1.        ]
 [0.38268156 0.83333333 0.3007335  1.        ]
 [0.27653631 0.86666667 0.29339853 1.        ]
 [0.         0.66666667 0.17359413 0.5       ]
 [0.08379888 0.46666667 0.00977995 0.5       ]
 [0.34916201 0.33333333 0.00733496 0.5       ]
 [0.80446927 0.3        0.14425428 0.        ]
 [0.53072626 0.53333333 0.34963325 0.        ]
 [0.15083799 0.86666667 0.78728606 0.        ]
 [0.01675978 0.93333333 0.47188264 0.5       ]
 [0.06703911 0.93333333 0.52811736 1.        ]
 [0.35195531 0.9        0.49388753 1.        ]
 [0.40782123 0.83333333 0.55256724 1.        ]
 [0.60893855 0.73333333 0.15403423 1.        ]
 [0.44692737 0.63333333 0.10513447 1.        ]
 [0.22346369 0.6        0.05867971 1.        ]
 [0.1396648  0.5        0.01711491 0.5       ]
 [0.26256983 0.3        0.00244499 0.        ]
 [0.73743017 

fp_normalisasi = pd.DataFrame(normalisasi, columns=['X1', 'X2', 'X3', 'Y'])  # menampilkan hasil normalisasi dataset dalam frame pandas 
fp_normalisasi 

In [7]:
ds_training = np.vstack(normalisasi[0:48,0:3])
print(ds_training)

[[0.18435754 1.         0.88508557]
 [0.26536313 0.93333333 0.        ]
 [0.31284916 0.9        0.73105134]
 [0.39664804 0.9        0.51100244]
 [0.38268156 0.83333333 0.3007335 ]
 [0.27653631 0.86666667 0.29339853]
 [0.         0.66666667 0.17359413]
 [0.08379888 0.46666667 0.00977995]
 [0.34916201 0.33333333 0.00733496]
 [0.80446927 0.3        0.14425428]
 [0.53072626 0.53333333 0.34963325]
 [0.15083799 0.86666667 0.78728606]
 [0.01675978 0.93333333 0.47188264]
 [0.06703911 0.93333333 0.52811736]
 [0.35195531 0.9        0.49388753]
 [0.40782123 0.83333333 0.55256724]
 [0.60893855 0.73333333 0.15403423]
 [0.44692737 0.63333333 0.10513447]
 [0.22346369 0.6        0.05867971]
 [0.1396648  0.5        0.01711491]
 [0.26256983 0.3        0.00244499]
 [0.73743017 0.23333333 0.01466993]
 [0.79329609 0.46666667 0.32518337]
 [0.27932961 0.86666667 0.76283619]
 [0.19553073 0.83333333 0.68459658]
 [0.12290503 0.76666667 0.98533007]
 [0.32402235 0.7        0.55745721]
 [0.24022346 0.7        0.74

In [8]:
ds_training.shape

(48, 3)

fp_dstraining = pd.DataFrame(ds_training, columns=['X1', 'X2', 'X3']) # menampilkan dataset training dalam frame pandas 
fp_dstraining 

In [9]:
ds_testing = np.vstack(normalisasi[48:60,0:3])
print(ds_testing)

[[0.22067039 0.76666667 0.44743276]
 [0.17877095 0.8        0.63325183]
 [0.30167598 0.76666667 0.53789731]
 [0.36592179 0.76666667 0.42298289]
 [0.40782123 0.6        0.19315403]
 [0.20111732 0.53333333 0.22493888]
 [0.12011173 0.36666667 0.06356968]
 [0.20111732 0.16666667 0.00977995]
 [0.51117318 0.06666667 0.08312958]
 [0.86312849 0.1        0.2591687 ]
 [0.45530726 0.3        0.50855746]
 [0.34916201 0.56666667 0.60880196]]


In [10]:
ds_testing.shape

(12, 3)

fp_dstesting = pd.DataFrame(ds_testing, columns=['X1', 'X2', 'X3']) # menampilkan dataset testing dalam frame pandas 
fp_dstesting 

import pandas as pd
pd_f000  = pd.DataFrame(normalisasi, columns=None)
writer = pd.ExcelWriter('Normalisasi.xlsx')
pd_f000.to_excel(writer, sheet_name = 'normalisasi', header = True, index = True)
writer.save()

import pandas as pd
pd_f001  = pd.DataFrame(ds_training, columns=None)
writer = pd.ExcelWriter('DataTraining.xlsx')
pd_f001.to_excel(writer, sheet_name = 'datatraining', header = True, index = True)
writer.save()

import pandas as pd
pd_f002  = pd.DataFrame(ds_testing, columns=None)
writer = pd.ExcelWriter('DataTesting.xlsx')
pd_f002.to_excel(writer, sheet_name = 'datatesting', header = True, index = True)
writer.save()

# Hidden layer

## Parameter Centers (Nilai Tengah Nilai Tengah)

In [11]:
l =47 # jumlah clusters dan jumlah centers setiap atribut input
def ChooseICenters(ds_training, l):#fungsi ChooseICenters dg inputs ds_training 45 x 3 & l (jumlah clusters atau panjang centers)
    # mengambil centers awal dr dataset training scr acak
    centers = ds_training[np.random.choice(ds_training.shape[0], l, replace = False)]
    return(centers) # ukurannya l x 3 (kolom 3 karena jml atribut input 3)

def EuclideanDistance(unit, center): # fungsi Euclidean Distance dg inputs unit & center 
    baris = len(unit)
    sum   = 0
    for i in range(baris):
        sum += (unit[i] - center[i]) ** 2
    return np.sqrt(sum)

def AssigntoClusters(ds_training, centers, clustering): # fungsi Assign to Clusters dg inputs ds_training, centers & clustering
    #diberikan array initial centers, ds_training akan terkluster di clusters
    clusters           = np.copy(clustering) # membuat sama ukuran array clusters baru dg input clustering
    (baris, kolom)     = ds_training.shape
    p                  = len(centers)
    
    EuclideanDistances = np.zeros(shape = (p), dtype = np.float32)# inisialisasi array Euclidean Distances ukuran (30, :)
    for i in range(baris): # i looping terus utk setiap ds_training
        for k in range(p): # k looping terus utk setiap centers
            EuclideanDistances[k] = EuclideanDistance(ds_training[i], centers[k]) #jarak dr ds_training ke setiap centers
        criterion    = np.argmin(EuclideanDistances) #menentukan setiap ds_training berada pada clusters tertentu sesuai kriteria jarak terdekat dengan centers
        clusters[i]  = criterion #setiap ds_training berclusters
            
    if np.array_equal(clustering, clusters): # array & elements clustering = array & elements clusters
        return False # saat kondisi berhenti (tidak ada perubahan terjadi) adalah salah
    
    calc = np.zeros(shape = (p), dtype = np.int) # inisialisasi array calc ukuran (p, :)
    for i in range(baris): # i looping terus utk setiap ds_training
        number = clustering[i]
        calc[number] += 1 #ukuran array (p,:) dan #memastikan tak ada clusters yang tidak terisi (kosong) atau jumlahnya = 0 dari anggota ds_training
    
    for k in range(p):  #menghitung ada atau tidaknya isi clusters (= np.count_nonzero)
        if calc[k] == 0: #clustering jelek jika ada yg bernilai nan=0 
            return False # saat kondisi ada cluster yg tak terisi (kosong) atau = 0 adalah salah
        
    for i in range(baris):
        clustering[i] = clusters[i] #clustering = clustering baru terisi
    return True # ada perubahan clustering = clusters
    #terjadi perubahan dan tidak ada cluster yg tak terisi (kosong) atau = 0
    #memperbaharui clustering = clusters

def RecomputeCenters(ds_training, centers, clustering):
    #ada clusters baru, akan menghitung centers baru
    #clusters terdapat di function AssigntoClusters dg tak ada clusters yg kosong atau = 0
    (baris, kolom) = ds_training.shape
    p              = len(centers)
    calc           = np.zeros(shape = (p), dtype = np.int) #inisialisasi jumlah ds_training telah terkluster di setiap clusters (p,:)
    newcenters     = np.zeros(shape = centers.shape, dtype = np.float32) # ukuran array sama dg centers (p x 3)
    for i in range(baris):
        number        = clustering[i]
        calc[number] += 1
        for j in range(kolom):
            newcenters[number,j] += ds_training[i,j] #akumulasi sigma ds_training
            
    for k in range(p):
        for j in range(kolom):
            newcenters[k,j] /= calc[k] #rumus temporary centers (step 4 Gupta Book) dan calc ~= 0 #61
    #rata-rata #calc = banyaknya ds_training di dalam setiap cluster ke-k
            
    for k in range(p): # looping sebanyak panjang array centers
        for j in range(kolom):
            centers[k,j] = newcenters[k,j] #temporary centers = newcenters (terupdate)

#menjalankan algoritma ke-4 dalam Gupta utk mendapatkan  centers dari rata-rata baru            
def TemporaryCenters(ds_training, p):
    (baris, kolom) = ds_training.shape
    clustering     = np.zeros(shape = (baris), dtype = np.int) #inisialisasi clustering ukuran array (p,:)
    centers        = np.zeros(shape = (p,kolom), dtype = np.float32)
    for k in range(p): # k looping terus utk setiap centers 
        clustering[k] = k
    for k in range(p, baris):
        clustering[k] = np.random.randint(0,p) #numbers klusters sebagai atribut: [0,p-1]; ukuran: 1x45 elemen2nya [0,p-1]
    RecomputeCenters(ds_training, centers, clustering) # running fungsi RecomputeCenters 
    return(clustering, centers)

def UpdatingCenters(ds_training, p):
    (clustering, centers) = TemporaryCenters(ds_training, p) #memanggil hasil dr step 1 s.d step 4 melalui fungsi RecomputeTCenters
    
    term         = True #asumsi benar jika ada sedikitnya unit ds_training berpindah ke lain cluster (clustering jelek)
    maxiteration = 100 #batas jumlah iterasi maksimum yg diterapkan
    epoch        = 1
    while epoch < maxiteration:
        epoch += 1 
        term = AssigntoClusters(ds_training, centers, clustering) #krn benar ada perpindahan, memasukkan ds_training ke cluster baru dg fungsi AssigntoClusters
        if term == False: #sudah tidak ada perpindahan ds_training ke cluster lain lagi
            break #selesai (prosedur berhenti)
        RecomputeCenters(ds_training, centers, clustering) #updating centers hingga tak ada lagi perpindahan ds_training ke cluster lain
    return(clustering, centers, epoch)

## Parameter Sigma (Standar Deviasi/Spread)

In [12]:
def sigma(centers, p):
    p              = len(centers)
    
    dmax          = 0
    for i in range(p):
        for j in range(p):
            if i == j:
                continue
            dist = EuclideanDistance(centers[i], centers[j])
            if dist > dmax:
                dmax = dist 
    sigma = dmax / np.sqrt(2*p)
    return sigma

## Fungsi Aktivasi Radial Basis

In [13]:
def gaussian(ds_training, centers, sigma):
    return np.exp(- EuclideanDistance(ds_training, centers)**2 / (2 * sigma**2))

def multiQuadratic(ds_training, centers, sigma):
    return np.power(EuclideanDistance(ds_training, centers)**2 + sigma **2, 0.5)

def inversMultiQuadratic(ds_training, centers, sigma):
    return np.power(EuclideanDistance(ds_training, centers)**2 + sigma **2, -0.5)

## Parameter Phi

In [14]:
def Phi(ds_training, centers, sigma):
    (baris, kolom) = ds_training.shape
    p              = len(centers)
    
    phi            = np.zeros(shape = (baris,p), dtype=np.float32)
    for i in range (baris):
        for j in range (p):
            phi[i,j] = gaussian(ds_training[i], centers[j], sigma)              #Gaussian Radial Basis Function
            #phi[i,j] = multiQuadratic(ds_training[i], centers[j], sigma)       #multiQuadratic RBF
            #phi[i,j] = inversMultiQuadratic(ds_training[i], centers[j], sigma) #inversMultiQuadratic RBF
    return(phi)

In [15]:
icenters            = ChooseICenters(ds_training, l)
print(icenters)

[[0.36592179 0.36666667 0.07823961]
 [0.18435754 1.         0.88508557]
 [0.57541899 0.3        0.15647922]
 [0.47206704 0.43333333 0.50366748]
 [0.15083799 0.86666667 0.78728606]
 [0.08379888 0.46666667 0.00977995]
 [0.32402235 0.7        0.55745721]
 [0.24022346 0.7        0.74816626]
 [0.2877095  0.8        1.        ]
 [0.60893855 0.73333333 0.15403423]
 [0.35195531 0.9        0.49388753]
 [0.34916201 0.33333333 0.00733496]
 [0.06703911 0.93333333 0.52811736]
 [0.65921788 0.56666667 0.41320293]
 [0.5726257  0.5        0.87286064]
 [0.39664804 0.9        0.51100244]
 [0.53072626 0.53333333 0.34963325]
 [0.1396648  0.5        0.01711491]
 [0.         0.66666667 0.17359413]
 [0.72346369 0.         0.        ]
 [0.22346369 0.6        0.05867971]
 [0.80446927 0.3        0.14425428]
 [0.01675978 0.93333333 0.47188264]
 [0.45810056 0.36666667 0.36919315]
 [0.27932961 0.86666667 0.76283619]
 [0.40782123 0.83333333 0.55256724]
 [0.58379888 0.56666667 0.55745721]
 [0.27932961 0.66666667 0.56

In [16]:
icenters.shape

(47, 3)

#simpan ke .xlsx
import pandas as pd
pd_f00  = pd.DataFrame(icenters, columns=None)
writer = pd.ExcelWriter('ICenters.xlsx')
pd_f00.to_excel(writer, sheet_name = 'icenters', header = None, index = None)
writer.save()

In [17]:
temporarycenters    = TemporaryCenters(ds_training, l)
tcenters            = temporarycenters[1]
print(tcenters)

[[0.18435754 1.         0.8850856 ]
 [0.26536313 0.93333334 0.        ]
 [0.31284916 0.9        0.7310513 ]
 [0.33798882 0.7833333  0.5403423 ]
 [0.38268158 0.8333333  0.3007335 ]
 [0.27653632 0.8666667  0.29339853]
 [0.         0.6666667  0.17359413]
 [0.08379889 0.46666667 0.00977995]
 [0.349162   0.33333334 0.00733496]
 [0.8044693  0.3        0.14425428]
 [0.53072625 0.53333336 0.34963325]
 [0.15083799 0.8666667  0.78728604]
 [0.01675978 0.93333334 0.47188264]
 [0.06703911 0.93333334 0.52811736]
 [0.3519553  0.9        0.49388754]
 [0.40782124 0.8333333  0.55256724]
 [0.6089386  0.73333335 0.15403423]
 [0.44692737 0.6333333  0.10513447]
 [0.22346368 0.6        0.05867971]
 [0.1396648  0.5        0.01711491]
 [0.26256984 0.3        0.00244499]
 [0.73743016 0.23333333 0.01466993]
 [0.7932961  0.46666667 0.32518336]
 [0.2793296  0.8666667  0.76283616]
 [0.19553073 0.8333333  0.6845966 ]
 [0.12290503 0.76666665 0.98533005]
 [0.32402235 0.7        0.5574572 ]
 [0.24022347 0.7        0.74

In [18]:
tcenters.shape

(47, 3)

In [19]:
tclusters            = temporarycenters[0]
print(tclusters)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46  3]


#simpan ke .xlsx
import pandas as pd
pd_f01  = pd.DataFrame(tcenters, columns=None)
pd_f02  = pd.DataFrame(tclusters)
writer = pd.ExcelWriter('TCenters_TClusters.xlsx')
pd_f01.to_excel(writer, sheet_name = 'tcenters', header = None, index = None)
pd_f02.to_excel(writer, sheet_name = 'tclusters', header = None, index = None)
writer.save()

In [20]:
import math
check=True
while check==True:
    updatecenters = UpdatingCenters(ds_training, l)
    centers       = updatecenters[1]
    check         = math.isnan(sum(sum(centers)))
print('========================================')
print('tidak ada nan')
print(centers)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:60: RuntimeWarning: invalid value encountered in true_divide


tidak ada nan
[[0.18435754 1.         0.8850856 ]
 [0.26536313 0.93333334 0.        ]
 [0.31284916 0.9        0.7310513 ]
 [0.39664805 0.9        0.5110024 ]
 [0.38268158 0.8333333  0.3007335 ]
 [0.27653632 0.8666667  0.29339853]
 [0.         0.6666667  0.17359413]
 [0.08379889 0.46666667 0.00977995]
 [0.349162   0.33333334 0.00733496]
 [0.8044693  0.3        0.14425428]
 [0.53072625 0.53333336 0.34963325]
 [0.15083799 0.8666667  0.78728604]
 [0.01675978 0.93333334 0.47188264]
 [0.06703911 0.93333334 0.52811736]
 [0.3519553  0.9        0.49388754]
 [0.40782124 0.8333333  0.55256724]
 [0.6089386  0.73333335 0.15403423]
 [0.44692737 0.6333333  0.10513447]
 [0.22346368 0.6        0.05867971]
 [0.1396648  0.5        0.01711491]
 [0.26256984 0.3        0.00244499]
 [0.73743016 0.23333333 0.01466993]
 [0.7932961  0.46666667 0.32518336]
 [0.2793296  0.8666667  0.76283616]
 [0.19553073 0.8333333  0.6845966 ]
 [0.12290503 0.76666665 0.98533005]
 [0.30167598 0.68333334 0.56356966]
 [0.24022347 0

In [21]:
clusters            = updatecenters[0]
print(clusters)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 26]


In [22]:
epoch               = updatecenters[2]                    
print(epoch)

3


In [23]:
#simpan ke .xlsx
import pandas as pd
pd_f03  = pd.DataFrame(centers, columns=None)
pd_f04  = pd.DataFrame(clusters)
writer = pd.ExcelWriter('Centers_Clusters.xlsx')
pd_f03.to_excel(writer, sheet_name = 'centers', header = 0, index = 0)
pd_f04.to_excel(writer, sheet_name = 'clusters', header = None, index = None)
writer.save()

In [24]:
sigma = sigma(centers, l)
print(sigma)

0.1485394128183331


In [25]:
phi = Phi(ds_training, centers, sigma)
print(phi)

[[1.00000000e+00 1.52022679e-08 3.20320725e-01 ... 2.80432491e-12
  4.96092305e-08 3.91993490e-06]
 [1.52022626e-08 1.00000000e+00 5.09452502e-06 ... 7.33273282e-06
  1.35723885e-05 4.19191338e-06]
 [3.20320785e-01 5.09452184e-06 1.00000000e+00 ... 3.38366917e-08
  5.06116085e-05 1.25415518e-03]
 ...
 [4.96091914e-08 1.35723867e-05 5.06116339e-05 ... 2.37405658e-01
  1.00000000e+00 5.97541571e-01]
 [3.91993399e-06 4.19191156e-06 1.25415600e-03 ... 3.41659114e-02
  5.97541630e-01 1.00000000e+00]
 [6.89698150e-03 1.27120540e-04 1.57339245e-01 ... 1.36044458e-04
  2.53581423e-02 1.13680571e-01]]


In [26]:
phi.shape

(48, 47)

In [27]:
import pandas as pd
pd_f06 = pd.DataFrame(phi, columns= None)
writer = pd.ExcelWriter('Phi.xlsx')
pd_f06.to_excel(writer, sheet_name = 'phi', header = None, index = None)
writer.save()

# Between Hidden Layer and Output Layer

In [28]:
da_y = np.vstack(normalisasi[0:48,3])
print(da_y)

[[0.5]
 [0.5]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [0.5]
 [0.5]
 [0.5]
 [0. ]
 [0. ]
 [0. ]
 [0.5]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [0.5]
 [0. ]
 [0.5]
 [0. ]
 [0. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [0.5]
 [0. ]
 [1. ]
 [0. ]
 [0. ]
 [0.5]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [1. ]
 [0.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]


In [29]:
day = np.vstack(dataset[0:48,3])
print(day)

[[2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [3.]
 [1.]
 [1.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [30]:
da_y.shape

(48, 1)

In [31]:
day.shape

(48, 1)

## Initial weights

In [32]:
w = np.transpose(np.random.randn(1,l))
print(w)

[[ 0.18128803]
 [ 0.55626958]
 [ 1.01522822]
 [-2.17074909]
 [-1.31489591]
 [ 0.24896177]
 [-0.54871646]
 [-0.23094115]
 [-0.2395029 ]
 [ 0.89658806]
 [-0.71786068]
 [ 1.60355346]
 [ 0.93097274]
 [-0.03152077]
 [-1.37810086]
 [-0.31061652]
 [ 0.55084808]
 [ 2.0417389 ]
 [-1.04708912]
 [-1.84148224]
 [-0.72553277]
 [ 1.33625866]
 [-0.00806161]
 [-1.61997232]
 [-0.19452208]
 [ 0.56065833]
 [-1.05559868]
 [-0.4298739 ]
 [-1.1431806 ]
 [ 0.80470607]
 [-0.28073354]
 [ 1.05423183]
 [ 1.01554509]
 [-0.38486822]
 [-1.17065286]
 [-0.91145535]
 [-0.27221072]
 [-0.37491124]
 [ 0.52149868]
 [ 0.37167855]
 [ 0.43772068]
 [ 0.03802347]
 [-0.7100993 ]
 [ 0.4071267 ]
 [-0.74500734]
 [-0.11933684]
 [ 1.06066874]]


In [33]:
w.shape

(47, 1)

import pandas as pd
pd_f07 = pd.DataFrame(w, columns= None)
writer = pd.ExcelWriter('Initial_Weights.xlsx')
pd_f07.to_excel(writer, sheet_name = 'iw', header = None, index = None)
writer.save()

In [34]:
def error(phi, da_y, w):
    (baris, kolom)     = da_y.shape
    p                  = len(w)
    e                  = np.zeros(shape=(da_y.shape), dtype=np.float32)
        
    sum3 = 0                 
    for i in range (baris):
        sum2 = 0             
        for j in range (p):
            sum2 += phi[i,j] * w[j]     
        e[i] = da_y[i] - sum2
        sum3 += e[i] ** 2         
    E = 0.5 * sum3               
    return(e, E)

In [35]:
error     = error(phi, da_y, w)
e         = error[0]
print(e) #the error signal produced at the output layer at iteration n training dataset (dg w random awal)

[[-0.12595071]
 [ 0.02627053]
 [ 2.2045522 ]
 [ 5.281634  ]
 [ 3.216531  ]
 [ 2.7187428 ]
 [ 1.7127608 ]
 [ 2.491757  ]
 [ 0.78988427]
 [-1.1765544 ]
 [-0.19378275]
 [-0.6476827 ]
 [-0.21791595]
 [ 0.56170255]
 [ 5.2739015 ]
 [ 4.9446516 ]
 [-0.12329999]
 [ 0.0361801 ]
 [ 3.3210504 ]
 [ 3.0242245 ]
 [ 0.06286103]
 [-0.97163105]
 [-0.37429452]
 [ 0.74896526]
 [ 1.7667223 ]
 [ 0.36467278]
 [ 3.6682286 ]
 [ 1.9933321 ]
 [ 2.7363272 ]
 [ 2.3732073 ]
 [ 1.8843607 ]
 [ 0.45132604]
 [-0.8359806 ]
 [ 0.9645807 ]
 [ 0.96452266]
 [ 0.9230907 ]
 [ 0.08411682]
 [ 1.0801897 ]
 [ 0.68169975]
 [ 0.3692791 ]
 [ 0.22235696]
 [ 1.7163924 ]
 [ 2.46414   ]
 [ 1.168762  ]
 [ 0.04172511]
 [ 0.09341071]
 [-0.6265691 ]
 [ 2.0931542 ]]


In [36]:
e.shape

(48, 1)

In [37]:
E     = error[1]
print(E) #the instantaneous error energy at the output layer (dg w random awal)

[97.27356]


import pandas as pd
pd_f08 = pd.DataFrame(e, columns= None)
pd_f09 = pd.DataFrame(E)
writer = pd.ExcelWriter('IErrors_e&E.xlsx')
pd_f08.to_excel(writer, sheet_name = 'ie', header = None, index = None)
pd_f09.to_excel(writer, sheet_name = 'E', header = None, index = None)
writer.save()

In [38]:
import sys

In [39]:
def Update_w_and_errors(phi, da_y, w, e, E):
    (baris,kolom) = da_y.shape
    p             = len(w)
    epoch         = 0
    alpha         = 0.01 #nilai learning rate
    
    maxiteration  = 5000
    while epoch < maxiteration: #and E > 0.1: #8
        epoch += 1
        for k in range (p):
            sum4 = 0
            for i in range (baris):
                sum4 +=  e[i] * phi[i,k]   #13
            w[k] += alpha * sum4          #14
            
        sum6 = 0
        for i in range (baris):
            sum5 = 0 
            for k in range (p):
                sum5 += phi[i,k] * w[k]  #21
            e[i]  = da_y[i] - sum5  #22
            sum6 += e[i] ** 2             #update error e #24
        E = 0.5 * sum6                    #update error E  #25
    return(w, e, E, epoch)

In [40]:
update_w_and_errors = Update_w_and_errors(phi, da_y, w, e, E)
w_update            = update_w_and_errors[0]                    
print(w_update)

[[ 0.87685377]
 [ 0.32314006]
 [ 1.96870937]
 [-0.70267375]
 [ 0.09957863]
 [ 0.64358644]
 [ 0.34777753]
 [-0.07885499]
 [ 0.24294269]
 [-0.14940851]
 [-1.75938507]
 [-1.71482593]
 [-0.68025048]
 [ 1.25567553]
 [ 0.43212004]
 [ 1.05696704]
 [ 0.78332419]
 [ 0.3642307 ]
 [ 0.9608209 ]
 [-1.53389928]
 [-1.51718356]
 [ 0.38712522]
 [-0.47227348]
 [-2.63087828]
 [ 1.55652455]
 [ 0.85224559]
 [-1.86188631]
 [ 1.28336449]
 [ 0.71598355]
 [ 1.58571586]
 [ 1.20049183]
 [ 0.08400931]
 [ 0.23503443]
 [ 0.90080506]
 [ 0.04115039]
 [-0.00754875]
 [-0.84964232]
 [ 0.68974298]
 [ 0.40573261]
 [ 0.72313103]
 [ 1.53079555]
 [ 1.91860151]
 [-0.3787597 ]
 [ 0.44614916]
 [-0.17320481]
 [ 0.16048284]
 [-0.44821741]]


In [41]:
import pandas as pd
pd_f010 = pd.DataFrame(w_update, columns= None)
writer = pd.ExcelWriter('Update_Weights.xlsx')
pd_f010.to_excel(writer, sheet_name = 'uw', header = None, index = None)
writer.save()

In [42]:
e_update            = update_w_and_errors[1]                    
print(e_update)

[[ 9.69157219e-02]
 [-6.00304594e-03]
 [ 3.26105058e-01]
 [-3.75724887e-03]
 [ 3.05885710e-02]
 [-6.68241503e-03]
 [ 1.31224031e-02]
 [-1.33130297e-01]
 [ 1.54977262e-01]
 [ 1.23720644e-02]
 [-1.80337906e-01]
 [-1.41146958e-01]
 [-9.52338949e-02]
 [ 7.48507157e-02]
 [-6.38759732e-02]
 [-2.88779475e-02]
 [-3.39217437e-03]
 [ 3.86310294e-02]
 [ 5.98681234e-02]
 [-1.09403558e-01]
 [-1.98853672e-01]
 [-1.09403282e-02]
 [-3.44198048e-02]
 [-4.89246637e-01]
 [ 2.51372606e-01]
 [ 1.64950434e-02]
 [ 3.40439618e-01]
 [ 1.39637351e-01]
 [ 4.71492335e-02]
 [ 2.87205964e-01]
 [ 1.63050026e-01]
 [-7.99446702e-02]
 [ 3.98623385e-02]
 [ 1.33569119e-03]
 [ 2.66177929e-04]
 [ 2.46767607e-03]
 [-6.52964935e-02]
 [ 2.83061359e-02]
 [-1.36616126e-01]
 [ 2.35046789e-01]
 [ 5.86272068e-02]
 [ 2.32021004e-01]
 [-1.09175898e-01]
 [-1.28689334e-01]
 [ 9.42512602e-03]
 [ 1.10428564e-01]
 [-1.67011902e-01]
 [-5.58036566e-01]]


In [43]:
E_update            = update_w_and_errors[2]                    
print(E_update)

[0.6812908]


import pandas as pd
pd_f011 = pd.DataFrame(e_update, columns= None)
pd_f012 = pd.DataFrame(E_update)
writer = pd.ExcelWriter('UErrors_e&E_RBFNN600HN2.xlsx')
pd_f011.to_excel(writer, sheet_name = 'e_update', header = None, index = None)
pd_f012.to_excel(writer, sheet_name = 'E', header = None, index = None)
writer.save()

In [44]:
epoch               = update_w_and_errors[3]                    
print(epoch)

5000


In [45]:
def Approximation_y(ds_training, centers, sigma, phi, w_update):
    (baris, kolom) = ds_training.shape
    p              = len(centers)
    F              = np.array(np.zeros([baris,1]), dtype=np.float32)
        
    sum7          = 0 #sum7
    for i in range (baris):
        for j in range (p):
            phi[i,j] = gaussian(ds_training[i], centers[j], sigma)              #Gaussian Radial Basis Function
            #phi[i,j] = multiQuadratic(ds_training[i], centers[j], sigma)       #multiQuadratic RBF
            #phi[i,j] = inversMultiQuadratic(ds_training[i], centers[j], sigma) #inversMultiQuadratic RBF
            sum7   += phi[i,j]*w_update[j]             
        F[i,0]       = sum7                                   
        sum7        = 0   
    return (F, phi, w_update)

In [46]:
Approximation_y = Approximation_y(ds_training, centers, sigma, phi, w_update)
approx_y        = Approximation_y[0]
print(approx_y)

[[ 4.03084278e-01]
 [ 5.06003022e-01]
 [ 6.73894942e-01]
 [ 1.00375724e+00]
 [ 9.69411433e-01]
 [ 1.00668240e+00]
 [ 4.86877590e-01]
 [ 6.33130312e-01]
 [ 3.45022738e-01]
 [-1.23720644e-02]
 [ 1.80337906e-01]
 [ 1.41146958e-01]
 [ 5.95233917e-01]
 [ 9.25149262e-01]
 [ 1.06387603e+00]
 [ 1.02887797e+00]
 [ 1.00339222e+00]
 [ 9.61368978e-01]
 [ 9.40131903e-01]
 [ 6.09403551e-01]
 [ 1.98853672e-01]
 [ 5.10940313e-01]
 [ 3.44198048e-02]
 [ 4.89246637e-01]
 [ 7.48627365e-01]
 [ 9.83504951e-01]
 [ 6.59560382e-01]
 [ 8.60362649e-01]
 [ 9.52850759e-01]
 [ 7.12794006e-01]
 [ 8.36950004e-01]
 [ 5.79944670e-01]
 [-3.98623385e-02]
 [ 9.98664320e-01]
 [-2.66177929e-04]
 [-2.46767607e-03]
 [ 5.65296471e-01]
 [ 9.71693873e-01]
 [ 1.13661611e+00]
 [ 7.64953196e-01]
 [ 9.41372812e-01]
 [ 7.67979026e-01]
 [ 1.10917592e+00]
 [ 6.28689349e-01]
 [-9.42512602e-03]
 [-1.10428564e-01]
 [ 1.67011902e-01]
 [ 5.58036566e-01]]


import pandas as pd
pd_f013 = pd.DataFrame(approx_y, columns= None)
writer = pd.ExcelWriter('F_Training_RBFNN600HN2.xlsx')
pd_f013.to_excel(writer, sheet_name = 'F', header = None, index = None)
writer.save()

In [47]:
phi_approx_y        = Approximation_y[1]
print(phi_approx_y)

[[1.00000000e+00 1.52022679e-08 3.20320725e-01 ... 2.80432491e-12
  4.96092305e-08 3.91993490e-06]
 [1.52022626e-08 1.00000000e+00 5.09452502e-06 ... 7.33273282e-06
  1.35723885e-05 4.19191338e-06]
 [3.20320785e-01 5.09452184e-06 1.00000000e+00 ... 3.38366917e-08
  5.06116085e-05 1.25415518e-03]
 ...
 [4.96091914e-08 1.35723867e-05 5.06116339e-05 ... 2.37405658e-01
  1.00000000e+00 5.97541571e-01]
 [3.91993399e-06 4.19191156e-06 1.25415600e-03 ... 3.41659114e-02
  5.97541630e-01 1.00000000e+00]
 [6.89698150e-03 1.27120540e-04 1.57339245e-01 ... 1.36044458e-04
  2.53581423e-02 1.13680571e-01]]


In [48]:
w_approx_y        = Approximation_y[2]
print(w_approx_y)

[[ 0.87685377]
 [ 0.32314006]
 [ 1.96870937]
 [-0.70267375]
 [ 0.09957863]
 [ 0.64358644]
 [ 0.34777753]
 [-0.07885499]
 [ 0.24294269]
 [-0.14940851]
 [-1.75938507]
 [-1.71482593]
 [-0.68025048]
 [ 1.25567553]
 [ 0.43212004]
 [ 1.05696704]
 [ 0.78332419]
 [ 0.3642307 ]
 [ 0.9608209 ]
 [-1.53389928]
 [-1.51718356]
 [ 0.38712522]
 [-0.47227348]
 [-2.63087828]
 [ 1.55652455]
 [ 0.85224559]
 [-1.86188631]
 [ 1.28336449]
 [ 0.71598355]
 [ 1.58571586]
 [ 1.20049183]
 [ 0.08400931]
 [ 0.23503443]
 [ 0.90080506]
 [ 0.04115039]
 [-0.00754875]
 [-0.84964232]
 [ 0.68974298]
 [ 0.40573261]
 [ 0.72313103]
 [ 1.53079555]
 [ 1.91860151]
 [-0.3787597 ]
 [ 0.44614916]
 [-0.17320481]
 [ 0.16048284]
 [-0.44821741]]


In [49]:
def denormalization(day, approx_y): 
    (baris,kolom)  = approx_y.shape
    mins           = np.zeros(shape=(kolom))
    maxs           = np.zeros(shape=(kolom))
    
    for jj in range (kolom):
        mins[jj] = np.min(day[:,jj])
        maxs[jj] = np.max(day[:,jj])
    
    hasil = np.copy(approx_y) #mendefinisikan hasil denormalisasi 45x3
    for i in range (baris):
        for jj in range (kolom):
            hasil[i,jj] = mins[jj] + (approx_y[i,jj]) * (maxs[jj]-mins[jj])
    return (hasil)

In [50]:
denormalize_ay = denormalization(day, approx_y) #menampilkan hasil dari fungsi denormalization  
print(denormalize_ay)

[[1.8061686 ]
 [2.012006  ]
 [2.3477898 ]
 [3.0075145 ]
 [2.9388227 ]
 [3.0133648 ]
 [1.9737551 ]
 [2.2662606 ]
 [1.6900455 ]
 [0.97525585]
 [1.3606758 ]
 [1.2822939 ]
 [2.1904678 ]
 [2.8502984 ]
 [3.127752  ]
 [3.057756  ]
 [3.0067844 ]
 [2.922738  ]
 [2.8802638 ]
 [2.2188072 ]
 [1.3977073 ]
 [2.0218806 ]
 [1.0688396 ]
 [1.9784932 ]
 [2.4972548 ]
 [2.96701   ]
 [2.319121  ]
 [2.7207253 ]
 [2.9057016 ]
 [2.4255881 ]
 [2.6739001 ]
 [2.1598892 ]
 [0.92027533]
 [2.9973288 ]
 [0.9994677 ]
 [0.9950647 ]
 [2.1305928 ]
 [2.9433877 ]
 [3.2732322 ]
 [2.5299063 ]
 [2.8827457 ]
 [2.535958  ]
 [3.2183518 ]
 [2.2573786 ]
 [0.98114973]
 [0.77914286]
 [1.3340238 ]
 [2.1160731 ]]


In [51]:
(m,n)    = np.shape(day)
gabung   = np.array(np.zeros([m,2]))
gabung[:,0]= day[:,0]
gabung[:,1]= denormalize_ay[:,0]
print(gabung)

[[2.         1.80616856]
 [2.         2.01200604]
 [3.         2.34778976]
 [3.         3.00751448]
 [3.         2.93882275]
 [3.         3.01336479]
 [2.         1.97375512]
 [2.         2.26626062]
 [2.         1.69004548]
 [1.         0.97525585]
 [1.         1.36067581]
 [1.         1.28229392]
 [2.         2.19046783]
 [3.         2.8502984 ]
 [3.         3.12775207]
 [3.         3.05775595]
 [3.         3.00678444]
 [3.         2.92273808]
 [3.         2.88026381]
 [2.         2.21880722]
 [1.         1.39770734]
 [2.         2.02188063]
 [1.         1.06883955]
 [1.         1.97849321]
 [3.         2.49725485]
 [3.         2.96701002]
 [3.         2.31912088]
 [3.         2.7207253 ]
 [3.         2.90570164]
 [3.         2.42558813]
 [3.         2.67390013]
 [2.         2.15988922]
 [1.         0.92027533]
 [3.         2.99732876]
 [1.         0.99946767]
 [1.         0.99506468]
 [2.         2.13059282]
 [3.         2.94338775]
 [3.         3.27323222]
 [3.         2.52990627]


import pandas as pd
pd_f014 = pd.DataFrame(gabung, columns= None)
writer = pd.ExcelWriter('TargetLatih_Asli_RBFNN600HN2.xlsx')
pd_f014.to_excel(writer, sheet_name = 'gabung', header = None, index = None)
writer.save()

In [52]:
rdenor = np.around(denormalize_ay)
print(rdenor)

[[2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [2.]
 [3.]
 [3.]
 [2.]
 [3.]
 [2.]
 [1.]
 [3.]
 [1.]
 [1.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [1.]
 [1.]
 [2.]]


In [53]:
(m,n)     = np.shape(day)
gabung2   = np.array(np.zeros([m,2]))
gabung2[:,0]= day[:,0]
gabung2[:,1]= rdenor[:,0]
print(gabung2)

[[2. 2.]
 [2. 2.]
 [3. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [2. 2.]
 [1. 1.]
 [2. 2.]
 [1. 1.]
 [1. 2.]
 [3. 2.]
 [3. 3.]
 [3. 2.]
 [3. 3.]
 [3. 3.]
 [3. 2.]
 [3. 3.]
 [2. 2.]
 [1. 1.]
 [3. 3.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [2. 2.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 2.]]


import pandas as pd
pd_f015 = pd.DataFrame(gabung2, columns= None)
writer = pd.ExcelWriter('TargetLatih_Akhir_RBFNN600HN2.xlsx')
pd_f015.to_excel(writer, sheet_name = 'gabung2', header = None, index = None)
writer.save()

In [54]:
def MAPE(day, denormalize_ay):
    mapeRBF = np.array(np.zeros([1,1]), dtype=np.float32)
    mapeRBF = np.mean(np.absolute(day - denormalize_ay)/day) * 100
    
    return(mapeRBF)

In [56]:
mape_RBF = MAPE(day, denormalize_ay)
print(mape_RBF)

13.687804341316223


import matplotlib.pyplot as plt

x = np.linspace(0, 1)

plt.xlim([0, 450])
plt.ylim([0.5, 5])

plt.plot(day, label='Aktual')

x = np.linspace(0, 1)

plt.xlim([0, 450])
plt.ylim([0.5, 5])

plt.plot(denormalize_ay, label='Pendekatan')

x = np.linspace(0, 450, num=449)

plt.plot(day, label='Aktual')
plt.plot(denormalize_ay, label='Pendekatan')

plt.xlabel('Index Per Bulan-Tahun')
plt.ylabel('Jumlah Produksi Udang Vannamei')

plt.title('Plot Data Aktual dan Data Pendekatan Produksi Udang Vannamei')

plt.legend()

plt.xlim([0, 450])
plt.ylim([0.5, 5])

plt.show()

x = np.linspace(0, 1)

plt.xlim([0, 450])
plt.ylim([0.5, 5])

plt.plot(rdenor, label='Pendekatanr')

x = np.linspace(0, 450, num=449)

plt.plot(day, label='Aktual')
plt.plot(rdenor, label='Pendekatan')

plt.xlabel('Index Per Bulan-Tahun')
plt.ylabel('Jumlah Produksi Udang Vannamei')

plt.title('Plot Data Aktual dan Data Pendekatan Produksi Udang Vannamei')

plt.legend()

plt.xlim([0, 450])
plt.ylim([0.5, 5])

plt.show()

# Testing

In [57]:
dayu = np.vstack(dataset[48:60,3])
print(dayu)

[[2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [58]:
dayu.shape

(12, 1)

In [68]:
def Approximation_yu(ds_testing, centers, sigma, phi, w_update):
    (baris, kolom) = ds_testing.shape
    p              = len(centers)
    F              = np.array(np.zeros([baris,1]), dtype=np.float32)
            
    sum7          = 0 
    for i in range (baris):
        for j in range (p):
            phi[i,j] = gaussian(ds_training[i], centers[j], sigma)
            sum7   += phi[i,j]*w_update[j]             
        F[i,0]       = sum7                                   
        sum7        = 0   
    return (F, w_update, phi)

In [69]:
approx_y_uji = Approximation_yu(ds_testing, centers, sigma, phi, w_update)
approx_yu    = approx_y_uji[0]
print(approx_yu)

[[ 0.40308428]
 [ 0.506003  ]
 [ 0.67389494]
 [ 1.0037572 ]
 [ 0.96941143]
 [ 1.0066824 ]
 [ 0.4868776 ]
 [ 0.6331303 ]
 [ 0.34502274]
 [-0.01237206]
 [ 0.1803379 ]
 [ 0.14114696]]


import pandas as pd
pd_f018 = pd.DataFrame(approx_yu, columns= None)
writer = pd.ExcelWriter('F_Testing_RBFNN600HN2.xlsx')
pd_f018.to_excel(writer, sheet_name = 'F', header = None, index = None)
writer.save()

In [70]:
w_approx_yu    = approx_y_uji[1]
print(w_approx_yu)

[[ 0.87685377]
 [ 0.32314006]
 [ 1.96870937]
 [-0.70267375]
 [ 0.09957863]
 [ 0.64358644]
 [ 0.34777753]
 [-0.07885499]
 [ 0.24294269]
 [-0.14940851]
 [-1.75938507]
 [-1.71482593]
 [-0.68025048]
 [ 1.25567553]
 [ 0.43212004]
 [ 1.05696704]
 [ 0.78332419]
 [ 0.3642307 ]
 [ 0.9608209 ]
 [-1.53389928]
 [-1.51718356]
 [ 0.38712522]
 [-0.47227348]
 [-2.63087828]
 [ 1.55652455]
 [ 0.85224559]
 [-1.86188631]
 [ 1.28336449]
 [ 0.71598355]
 [ 1.58571586]
 [ 1.20049183]
 [ 0.08400931]
 [ 0.23503443]
 [ 0.90080506]
 [ 0.04115039]
 [-0.00754875]
 [-0.84964232]
 [ 0.68974298]
 [ 0.40573261]
 [ 0.72313103]
 [ 1.53079555]
 [ 1.91860151]
 [-0.3787597 ]
 [ 0.44614916]
 [-0.17320481]
 [ 0.16048284]
 [-0.44821741]]


In [71]:
phi_approx_yu    = approx_y_uji[2]
print(phi_approx_yu)

[[1.00000000e+00 1.52022679e-08 3.20320725e-01 ... 2.80432491e-12
  4.96092305e-08 3.91993490e-06]
 [1.52022626e-08 1.00000000e+00 5.09452502e-06 ... 7.33273282e-06
  1.35723885e-05 4.19191338e-06]
 [3.20320785e-01 5.09452184e-06 1.00000000e+00 ... 3.38366917e-08
  5.06116085e-05 1.25415518e-03]
 ...
 [4.96091914e-08 1.35723867e-05 5.06116339e-05 ... 2.37405658e-01
  1.00000000e+00 5.97541571e-01]
 [3.91993399e-06 4.19191156e-06 1.25415600e-03 ... 3.41659114e-02
  5.97541630e-01 1.00000000e+00]
 [6.89698150e-03 1.27120540e-04 1.57339245e-01 ... 1.36044458e-04
  2.53581423e-02 1.13680571e-01]]


In [72]:
denormalize_ayu = denormalization(dayu, approx_yu) #menampilkan hasil dari fungsi denormalization  
print(denormalize_ayu)

[[1.8061686 ]
 [2.012006  ]
 [2.3477898 ]
 [3.0075145 ]
 [2.9388227 ]
 [3.0133648 ]
 [1.9737551 ]
 [2.2662606 ]
 [1.6900455 ]
 [0.97525585]
 [1.3606758 ]
 [1.2822939 ]]


In [73]:
(m,n)     = np.shape(dayu)
gabung3   = np.array(np.zeros([m,2]))
gabung3[:,0]= dayu[:,0]
gabung3[:,1]= denormalize_ayu[:,0]
print(gabung3)

[[2.         1.80616856]
 [3.         2.01200604]
 [3.         2.34778976]
 [3.         3.00751448]
 [3.         2.93882275]
 [3.         3.01336479]
 [3.         1.97375512]
 [2.         2.26626062]
 [1.         1.69004548]
 [1.         0.97525585]
 [1.         1.36067581]
 [1.         1.28229392]]


import pandas as pd
pd_f016 = pd.DataFrame(gabung3, columns= None)
writer = pd.ExcelWriter('TargetUji_Asli_RBFNN600HN2.xlsx')
pd_f016.to_excel(writer, sheet_name = 'gabung3', header = None, index = None)
writer.save()

In [74]:
rdenor2 = np.around(denormalize_ayu)
print(rdenor2)

[[2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]]


In [75]:
(m,n)     = np.shape(dayu)
gabung4   = np.array(np.zeros([m,2]))
gabung4[:,0]= dayu[:,0]
gabung4[:,1]= rdenor2[:,0]
print(gabung4)

[[2. 2.]
 [3. 2.]
 [3. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 2.]
 [2. 2.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


import pandas as pd
pd_f017 = pd.DataFrame(gabung4, columns= None)
writer = pd.ExcelWriter('TargetUji_Akhir_RBFNN600HN2.xlsx')
pd_f017.to_excel(writer, sheet_name = 'gabung4', header = None, index = None)
writer.save()

In [76]:
mape_RBF2 = MAPE (dayu, denormalize_ayu)
print(mape_RBF2)

20.866449342833626


x = np.linspace(0, 1)

plt.xlim([0, 150])
plt.ylim([0.5, 5])

plt.plot(dayu, label='Aktual')

x = np.linspace(0, 1)

plt.xlim([0, 150])
plt.ylim([0.5, 5])

plt.plot(denormalize_ayu, label='Pendekatan')

x = np.linspace(0, 150, num=149)

plt.plot(dayu, label='Aktual')
plt.plot(denormalize_ayu, label='Pendekatan')

plt.xlabel('Index Per Bulan-Tahun')
plt.ylabel('Jumlah Produksi Udang Vannamei')

plt.title('Plot Data Aktual dan Data Pendekatan Produksi Udang Vannamei')

plt.legend()

plt.xlim([0, 150])
plt.ylim([0.5, 5])

plt.show()

x = np.linspace(0, 1)

plt.xlim([0, 150])
plt.ylim([0.5, 5])

plt.plot(rdenor2, label='Pendekatanr')

x = np.linspace(0, 150, num=149)

plt.plot(dayu, label='Aktual')
plt.plot(rdenor2, label='Pendekatan')

plt.xlabel('Index Per Bulan-Tahun')
plt.ylabel('Jumlah Produksi Udang Vannamei')

plt.title('Plot Data Aktual dan Data Pendekatan Produksi Udang Vannamei')

plt.legend()

plt.xlim([0, 150])
plt.ylim([0.5, 5])

plt.show()